"""Add relationships

Revision ID: 14054bbf32ab
Revises: 99f4a7ffd88a
Create Date: 2023-12-11 19:28:10.176540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14054bbf32ab'
down_revision = '99f4a7ffd88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baked_goods', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
