"""Updates

Revision ID: 99f4a7ffd88a
Revises: df958add3ef8
Create Date: 2023-11-24 12:45:12.575041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f4a7ffd88a'
down_revision = 'df958add3ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
